# Generated by Django 3.0.4 on 2020-03-22 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('web_url', models.URLField()),
                ('query_url', models.URLField()),
                ('contact_num', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('charge', models.FloatField()),
                ('last_updated', models.DateField(auto_now_add=True, verbose_name='last updated')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='procedures.Hospital')),
            ],
        ),
    ]
